# Generated by Django 5.1.4 on 2024-12-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='ball_speed_x',
            field=models.FloatField(default=0.005),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='ball_speed_y',
            field=models.FloatField(default=0.005),
        ),
    ]
