# Generated by Django 5.1.2 on 2024-11-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='player1',
            field=models.CharField(default='Player 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
