# Generated by Django 5.1.2 on 2024-11-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='game_type',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
