# Generated by Django 5.1.2 on 2024-11-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='player1',
            field=models.CharField(default='Player 1', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player2',
            field=models.CharField(default='Player 2', max_length=255, unique=True),
        ),
    ]
