# Generated by Django 5.1.4 on 2024-12-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_gamestate_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
