# Generated by Django 5.1.4 on 2024-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_gamestate_ball_speed_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='ball_speed_x',
            field=models.FloatField(default=0.002),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='ball_speed_y',
            field=models.FloatField(default=0.002),
        ),
    ]
