
services:
  auth-db:
    container_name: auth-db
    build: ./../backend/user-management/auth-service/postgres
    environment:
      POSTGRES_USER: ${AUTH_SERVICE_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_PASSWORD}
      POSTGRES_DB: ${AUTH_SERVICE_DB}
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      my_network:
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /var/lib/postgresql/data/.db_ready ] || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"

  user-db:
    container_name: user-db
    build: ./../backend/user-management/user-service/postgres
    environment:
      POSTGRES_USER: ${USER_SERVICE_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_DB}
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      my_network:
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /var/lib/postgresql/data/.db_ready ] || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5433:5432"

  match-history-db:
    container_name: match-history-db
    build: ./../backend/user-management/match-history-service/postgres
    environment:
      POSTGRES_USER: ${MATCH_SERVICE_USER}
      POSTGRES_PASSWORD: ${MATCH_SERVICE_PASSWORD}
      POSTGRES_DB: ${MATCH_SERVICE_DB}
    volumes:
      - match_history_data:/var/lib/postgresql/data
    networks:
      my_network:
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /var/lib/postgresql/data/.db_ready ] || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5434:5432"

  auth-service:
    build: ./../backend/user-management/auth-service
    container_name: auth-service
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      AUTH_SERVICE_DB: ${AUTH_SERVICE_DB}
      AUTH_SERVICE_USER: ${AUTH_SERVICE_USER}
      AUTH_SERVICE_PASSWORD: ${AUTH_SERVICE_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      REDIS_URL: "redis://redis:6379"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_DB: 0
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      SHARED_SECRET: ${SHARED_SECRET}
    networks:
      my_network:
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8000/auth/health/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      auth-db:
        condition: service_healthy
    restart: always
    ports:
      - "8000:8000"

  user-service:
    build: ./../backend/user-management/user-service
    container_name: user-service
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      USER_SERVICE_DB: ${USER_SERVICE_DB}
      USER_SERVICE_USER: ${USER_SERVICE_USER}
      USER_SERVICE_PASSWORD: ${USER_SERVICE_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      SHARED_SECRET: ${SHARED_SECRET}
    networks:
      my_network:
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8000/users/health/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      user-db:
        condition: service_healthy
    restart: always
    ports:
      - "8001:8000"

  chat-service:
    build: ./../backend/chat-service
    container_name: chat-service
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      REDIS_URL: "redis://redis:6379"
    networks:
      my_network:
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8000/chat/health/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    ports:
      - "8003:8000"

  match-history-service:
    build: ./../backend/user-management/match-history-service
    container_name: match-history-service
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      MATCH_SERVICE_DB: ${MATCH_SERVICE_DB}
      MATCH_SERVICE_USER: ${MATCH_SERVICE_USER}
      MATCH_SERVICE_PASSWORD: ${MATCH_SERVICE_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      REDIS_URL: "redis://redis:6379"
    networks:
      my_network:
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8000/match/health/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      match-history-db:
        condition: service_healthy
    restart: always
    ports:
      - "8005:8000"

  pong-game:
    build: ./../backend/pong
    volumes:
      - ./../backend/pong:/app
    container_name: pong
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      REDIS_URL: "redis://redis:6379"
    working_dir: /app
    networks:
      my_network:
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8000/pong/health/ || exit 1" ]
      interval: 3s
      timeout: 5s
      retries: 5
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    ports:
      - "8002:8000"

  lobby:
    build: ./../backend/lobby
    volumes:
      - ./../backend/lobby:/app
    container_name: lobby
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      REDIS_URL: "redis://redis:6379"
    working_dir: /app
    networks:
      my_network:
    healthcheck:
      test: [ "CMD-SHELL", "curl -k -f http://localhost:8000/lobby/health/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "8004:8000"

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      my_network:
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always

  nginx:
    build: ./../frontend
    container_name: nginx
    depends_on:
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      chat-service:
        condition: service_healthy
      pong-game:
        condition: service_healthy
      lobby:
        condition: service_healthy
      match-history-service:
        condition: service_healthy
    networks:
      my_network:
    ports:
      - "80:80"
      - "443:443"
    restart: always

networks:
  my_network:

volumes:
  user_data:
  auth_data:
  redis_data:
  match_history_data:
