version: '3.9'

services:
  db:
    container_name: postgres_db
    build: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      my_network:
    healthcheck:
      test: ["CMD-SHELL", "[ -f /var/lib/postgresql/data/.db_ready ] || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
  
  backend:
    build: ./../backend
    container_name: backend
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      my_network:
    volumes:
      - backend_data:/app
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8000:8000"

networks:
  my_network:

volumes:
  db_data:
  backend_data:
