# Generated by Django 5.1.2 on 2024-11-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gameRoom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
