# Generated by Django 5.1.2 on 2024-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.CharField(default='No room', max_length=255),
        ),
    ]
