# Generated by Django 5.1.2 on 2024-11-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_tournament_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='num_players',
            field=models.IntegerField(default=0),
        ),
    ]
