# Generated by Django 5.1.2 on 2024-12-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_alter_player_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
