# Generated by Django 5.1.2 on 2024-12-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_alter_tournament_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='matches',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
