# Generated by Django 5.1.4 on 2024-12-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_tournament_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.CharField(default='No winner', max_length=255),
        ),
    ]
